[functions.update-campaign-analytics]
enabled = true
verify_jwt = true
import_map = "./functions/update-campaign-analytics/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-campaign-analytics/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-campaign-analytics/*.html" ]

[auth]
# Enable email confirmations for new signups
email = { enable_confirmations = true }

# Optional: Customize email templates
[auth.email.template.confirmation]
subject = "Confirm Your Signup"
content_path = "./supabase/templates/confirmation.html"